In [ ]:
#extract covaraince for my use from lane et al.
#Caution :Code is still ugly
import pandas as pd
import numpy as np


from astropy.coordinates import SkyCoord
import astropy.units as u

import matplotlib.pyplot as plt
path='/Storage/animesh/DATA_PPLUS'

PAN=pd.read_csv(path+'/Pantheon+SH0ES.dat',delimiter=' ')
df= pd.read_csv('/Storage/animesh/Analysis_C2/full_input.csv')
Z=pd.read_csv(path+'/Zpan.csv')
len(PAN)


Series([], Name: 0, dtype: object)

In [22]:
lane=np.load('index_sorted_lane.npy')

In [30]:
ix=PAN[PAN['zHEL']>=0.8].index

In [29]:
pan_lane=PAN.loc[lane]
ix_lane=pan_lane[pan_lane['zHEL']>=0.8].index

In [33]:
ix[~np.in1d(ix,ix_lane)]

Index([1694], dtype='int64')

In [35]:
pan_lane[pan_lane['zHEL']>=0.8]

CID  IDSURVEY      zHD   zHDERR     zCMB  zCMBERR     zHEL  \
1670      03D1fq         4  0.79863  0.01011  0.79858   0.0100  0.80000   
1672       Spock       100  0.83981  0.00161  0.83973   0.0005  0.83900   
1671       Elvis       100  0.83981  0.00523  0.83973   0.0050  0.83900   
1673    Manipogo       100  0.85482  0.00163  0.85474   0.0005  0.85400   
1674       Vilas       100  0.93585  0.00525  0.93577   0.0050  0.93500   
1675        Ombo       100  0.97423  0.00172  0.97424   0.0005  0.97500   
1676     SCP05D0       101  1.01242  0.00175  1.01236   0.0005  1.01400   
1677       Eagle       100  1.01988  0.00176  1.01980   0.0005  1.01900   
1678    Ferguson       100  1.02088  0.00528  1.02081   0.0050  1.02000   
1679    Strolger       100  1.02789  0.00176  1.02781   0.0005  1.02700   
1680     SCP06U4       101  1.04817  0.00178  1.04819   0.0005  1.05000   
1681        Gabi       100  1.12092  0.00530  1.12085   0.0050  1.12000   
1682     SCP06H5       101  1.23225  0.00193  1.23223   0.0005  1.23099   
1683   Lancaster       100  1.23597  0.00193  1.23589   0.0005  1.23500   
1684   Aphrodite       100  1.29911  0.00535  1.29912   0.0050  1.30001   
1685       Thoth       100  1.30410  0.00199  1.30412   0.0005  1.30501   
1686      Inanna       100  1.30611  0.00199  1.30612   0.0005  1.30701   
1687     SCP05D6       101  1.31317  0.00199  1.31311   0.0005  1.31500   
1688  washington       106  1.32910  0.02009  1.32911   0.0200  1.33001   
1689        Borg       100  1.34101  0.00537  1.34093   0.0050  1.34000   
1690     SCP06G4       101  1.35136  0.00202  1.35134   0.0005  1.34999   
1691     Mcguire       100  1.35608  0.00203  1.35610   0.0005  1.35701   
1692   Sasquatch       100  1.39103  0.00538  1.39096   0.0050  1.39000   
1693     SCP06K0       101  1.41633  0.00208  1.41631   0.0005  1.41499   
1695       Primo       106  1.54901  0.00213  1.54903   0.0001  1.55001   
1696    rutledge       106  1.61505  0.00545  1.61499   0.0050  1.61399   
1697        geta       106  1.69706  0.04006  1.69702   0.0400  1.70000   
1698       stone       106  1.80119  0.02014  1.80111   0.0200  1.80000   
1699      wilson       106  1.91165  0.00263  1.91160   0.0010  1.91401   
1700      colfax       106  2.26137  0.02018  2.26130   0.0200  2.26000   

      zHELERR  m_b_corr  m_b_corr_err_DIAG  ...  PKMJDERR  NDOF   FITCHI2  \
1670   0.0100   24.1808           0.286876  ...    0.6618    14  11.34630   
1672   0.0005   23.9482           0.389488  ...    0.5596    13  14.34930   
1671   0.0050   24.1070           0.210118  ...    0.7950     9  21.75830   
1673   0.0005   24.3638           0.298695  ...    0.8021     5  16.31310   
1674   0.0050   24.2801           0.238415  ...    1.3783     9  35.79780   
1675   0.0005   24.8581           0.199702  ...    0.5447    11  38.80640   
1676   0.0005   24.8647           0.366090  ...    0.8414     6   2.34822   
1677   0.0005   25.0227           0.224284  ...    0.6612     7  17.85840   
1678   0.0050   24.7176           0.474703  ...    6.1904     5  11.67410   
1679   0.0005   25.2834           0.352352  ...    4.8323     5   3.62750   
1680   0.0005   25.1699           0.488011  ...    0.1929     5   4.07764   
1681   0.0050   25.1875           0.221994  ...    0.5227     6  16.67940   
1682   0.0005   25.0677           0.609899  ...    1.4194     4   8.10259   
1683   0.0005   25.6520           0.272400  ...    1.5307     9  11.09250   
1684   0.0050   25.6111           0.273963  ...    0.6228    10  28.54230   
1685   0.0005   25.4676           0.315363  ...    2.8940     5  12.51340   
1686   0.0005   25.7667           0.444343  ...    5.6997     2   1.72179   
1687   0.0005   25.5337           0.315195  ...    1.3273     7   8.23115   
1688   0.0200   25.6215           0.236810  ...    3.2842     9  20.75470   
1689   0.0050   25.5011           0.305203  ...    2.1746     8  11.96180   
1690   0.0005   25.2962           0.317314  ...    1.1474     6   5.25

In [59]:
PAN[PAN['zHEL']>=0.8][['CID','RA','DEC','PKMJD','zHEL']]

CID        RA      DEC    PKMJD     zHEL
1670      03D1fq   36.7319  -4.3022  52999.1  0.80000
1671       Elvis  189.4510  62.2265  52783.7  0.83900
1672       Spock  189.2770  62.2533  53401.3  0.83900
1673    Manipogo  189.1450  62.2636  53150.4  0.85400
1674       Vilas  189.3710  62.1911  52726.8  0.93500
1675        Ombo   53.1056 -27.7508  53369.4  0.97500
1676     SCP05D0   35.4253  -3.3648  53607.1  1.01400
1677       Eagle  189.3370  62.2282  53295.6  1.01900
1678    Ferguson  189.1050  62.2566  53466.4  1.02000
1679    Strolger  189.0860  62.1807  53469.9  1.02700
1680     SCP06U4  356.3730 -36.5460  53939.2  1.05000
1681        Gabi  189.0580  62.2021  53489.2  1.12000
1682     SCP06H5  218.6260  34.4492  53860.7  1.23099
1683   Lancaster  189.2360  62.2148  53432.5  1.23500
1684   Aphrodite   53.1563 -27.7796  52552.8  1.30001
1685       Thoth   53.1033 -27.7716  52571.0  1.30501
1686      Inanna   53.1847 -27.9184  52668.1  1.30701
1687     SCP05D6   35.4437  -3.3823  53658.8  1.31500
1688  washington   53.0869 -27.8282  55616.9  1.33001
1689        Borg  189.2880  62.1914  52736.6  1.34000
1690     SCP06G4  217.3280  34.6437  53859.7  1.34999
1691     Mcguire   53.0418 -27.8305  53264.2  1.35701
1692   Sasquatch  189.2250  62.1397  53145.9  1.39000
1693     SCP06K0  219.5350  34.2384  53747.5  1.41499
1694      carter  150.0610   2.1924  55943.2  1.54000
1695       Primo   53.1584 -27.7775  55483.3  1.55001
1696    rutledge  215.2000  53.0728  56456.5  1.61399
1697        geta  322.3500   0.1402  56139.6  1.70000
1698       stone  189.3200  62.2782  56481.9  1.80000
1699      wilson   34.4431  -5.2566  55539.3  1.91401
1700      colfax  189.1570  62.3092  56078.3  2.26000

1701

In [66]:
mask

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ...,  True, False, False],
       [False, False, False, ..., False, False,  True],
       [False, False, False, ..., False, False, False]])

In [67]:
#150.0610	2.1924	55943.2
#SURVEYCOMPARE=abs(np.array(PAN['IDSURVEY'])[:,np.newaxis]==np.array(df['IDSURVEY']))
MJDCOMPARE=abs(np.isclose(np.array(df['zHEL']),1.54,atol=1e-2))
mask1=MJDCOMPARE

df[mask1]

Unnamed: 0      zCMB        mB       x1         c  HOST_LOGMASS  \
1641  Primo_106.0  1.549024  25.74805 -0.51191 -0.201856          9.46   

      IDSURVEY     zHEL         RA      DEC    x1ERR      cERR  COV_x1_c  
1641     106.0  1.55001  53.158401 -27.7775  0.41103  0.076883  0.004352

In [9]:
mat = np.empty((len(PAN), len(df)), dtype=object)
rows = len(PAN)
cols = len(df)

# Create the i and j indices arrays
i_indices = np.arange(rows)[:, None]  # Shape (rows, 1)
j_indices = np.arange(cols)           # Shape (cols,)

# Combine i and j indices into one array
mat = np.stack(np.meshgrid(i_indices, j_indices, indexing='ij'), axis=-1)

# Example usage

SURVEYCOMPARE=abs(np.array(PAN['IDSURVEY'])[:,np.newaxis]==np.array(df['IDSURVEY']))
ZHELCOMPARE=abs(np.array(PAN['zHEL'])[:,np.newaxis]==np.array(df['zHEL']))
cCOMPARE=abs(np.array(PAN['c'])[:,np.newaxis]-np.array(df['c']))<0.00001

mask=SURVEYCOMPARE  & cCOMPARE
arr=np.array(mat[mask])


In [10]:
panindex=mat[mask][:,0]
lane_index=mat[mask][:,1]   

dictionary = dict(arr)

In [6]:
sorted_arr = arr[arr[:, 1].argsort()]

print(sorted_arr)

[[1027    0]
 [1071    1]
 [1378    2]
 ...
 [1698 1687]
 [1688 1688]
 [1699 1689]]


In [4]:
cov_proper=np.loadtxt('/Storage/animesh/Analysis_C2/PP_1690_COVd.txt')


In [ ]:
cov_proper.shape

In [ ]:
#for i,j in arr:
#    print(df.loc[j]['Unnamed: 0'],PAN.loc[i]['CID'],'_',PAN.loc[i]['IDSURVEY'])

In [7]:
#PAN=PAN.sort_values('zHEL')
PAN=pd.read_csv(path+'/Pantheon+SH0ES.dat',delimiter=' ')
PAN['NAME']=PAN['CID'].astype(str) + '_' + PAN['IDSURVEY'].astype(float).astype(str)
PAN=PAN.sort_values('zHEL')

mat = np.empty((len(PAN), len(df)), dtype=object)
rows = len(PAN)
cols = len(df)
# Create the i and j indices arrays
i_indices = np.arange(rows)[:, None]  # Shape (rows, 1)
j_indices = np.arange(cols)           # Shape (cols,)

# Combine i and j indices into one array
mat = np.stack(np.meshgrid(i_indices, j_indices, indexing='ij'), axis=-1)
# Example usage
NAMECOMPARE=abs(np.array(PAN['NAME'])[:,np.newaxis]==np.array(df['Unnamed: 0']))
mask=NAMECOMPARE

PAN_SORTED_INDEX=np.array(PAN.index)



panindex=mat[mask][:,0]
lane_index=mat[mask][:,1]   

arr=np.array(mat[mask])
sorted_pairing = arr[arr[:, 1].argsort()]
ix_df = sorted_pairing[:, 1]
index_lane = sorted_pairing[:, 0]

dictionary = dict(arr)
newkeys = np.array(PAN.index[np.in1d(PAN.index, arr[:, 0])])
index_cov_sorted_zhel = np.array([dictionary[k] for k in newkeys])
tempind=np.array([[3*i,3*i+1,3*i+2] for i in index_cov_sorted_zhel ])
tempind=tempind.flatten(order='c')

cov_final = cov_proper[:, tempind][tempind]


NameError: name 'cov_proper' is not defined

In [ ]:
tempind[51]/3

In [ ]:
arr[:20]

In [ ]:
tempind[18]/3

In [ ]:
arr[6]

In [ ]:
cov_final[:,5*3][5*3]

In [ ]:
cov_proper[:,683*3][683*3]

In [ ]:
np.save('cov_final', cov_final)

#tempind=np.array([[3*i,3*i+1,3*i+2] for i in index_cov_sorted_zhel ])
#tempind=tempind.flatten(order='c')

np.save('index_sorted_lane',newkeys)

In [ ]:
np.load('/Storage/animesh/Analysis_C2/index_sorted_lane.npy')

In [ ]:
ix=345
PAN.loc[ix]

In [ ]:
ix_lane

In [ ]:
ix

In [ ]:
PAN.index[ix]

In [ ]:
51/3

In [ ]:
np.where(cov_final==0.0032551409747765816)

In [3]:
ix=1432
ix_lane=dictionary[ix]
temp=3*ix_lane
print(ix_lane)
print(df.iloc[ix_lane]['Unnamed: 0'],PAN.iloc[ix].CID)
print(cov_proper[3*ix_lane,3*ix_lane],cov_final[3*PAN.index[ix],3*PAN.index[ix]])
print(cov_proper[3*ix_lane,3*ix_lane],cov_final[3*ix,3*ix])

NameError: name 'dictionary' is not defined

In [4]:
Z1 = pd.read_csv(path+'/Zpan.csv')
df1=pd.read_csv( path+'/Pantheon+SH0ES.dat',delimiter=' ')

Z1['mB'] = Z1['mB'] + df1['biasCor_m_b']
Z1=Z1.loc[newkeys]
Z1=Z1.reset_index(drop=True)
#Z=Z[Z['zHEL']<0.8]
Z1.zHEL[400]
l1=Z1.index
COVd1 = np.load('/Storage/animesh/Analysis_C2/cov_final.npy')
tempind1=np.array([[3*i,3*i+1,3*i+2] for i in l1])
tempind1=tempind1.flatten(order='c')


n1=134
tempind1=np.array([[3*i,3*i+1,3*i+2] for i in [n1]])
tempind1=tempind1.flatten(order='c')

print('Z is:',Z1.iloc[n1].zHEL,'\n COV elements are: \n', COVd1[:,tempind1][tempind1])

NameError: name 'newkeys' is not defined

In [ ]:
print(df[df.zHEL==0.01219] .index[0])
n2=df[df.zHEL==0.01219].index[0]
tempind2=np.array([[3*i,3*i+1,3*i+2] for i in [n2]])
tempind2=tempind2.flatten(order='c')
print('Z is:',df.iloc[n2].zHEL,'\n COV elements are: \n',cov_proper[:,tempind2][tempind2])

In [5]:
cov_proper=np.loadtxt('/Storage/animesh/Analysis_C2/PP_1690_COVd.txt')


In [67]:
PAN=pd.read_csv(path+'/Pantheon+SH0ES.dat',delimiter=' ')
PAN['NAME']=PAN['CID'].astype(str) + '_' + PAN['IDSURVEY'].astype(float).astype(str)
df=pd.read_csv('/Storage/animesh/Analysis_C2/full_input.csv')
df['cov_elements']=np.diag(cov_proper)[::3]
rows = len(PAN)
cols = len(df)
# Create the i and j indices arrays
i_indices = np.arange(rows)[:, None]  # Shape (rows, 1)
j_indices = np.arange(cols)           # Shape (cols,)
# Combine i and j indices into one array
mat = np.stack(np.meshgrid(i_indices, j_indices, indexing='ij'), axis=-1)
NAMECOMPARE=np.array(PAN['NAME'])[:,np.newaxis]==np.array(df['Unnamed: 0'])
mask=NAMECOMPARE
pairing=mat[mask]

PAN=PAN.sort_values('zHEL')

newkeys1=PAN.index[np.in1d(PAN.index,pairing[:,0])]
dictionary=dict(pairing)
index_temp=[dictionary[j] for j in newkeys1]    
ind3n3n=np.array([[3*i,3*i+1,3*i+2] for i in index_temp])
ind3n3n=ind3n3n.flatten(order='c')
cov_final1=cov_proper[:,ind3n3n][ind3n3n]
indnn=np.array([[3*i] for i in index_temp])
indnn=indnn.flatten(order='c')
cov_nn=cov_proper[indnn][:,indnn]

In [7]:
np.save('cov_final',cov_final1)
np.save('cov_nn',cov_nn)

np.save('index_sorted_lane',newkeys1)

In [75]:
Z1 = pd.read_csv(path+'/Zpan.csv')
df1=pd.read_csv( path+'/Pantheon+SH0ES.dat',delimiter=' ')

Z1['mB'] = Z1['mB'] + df1['biasCor_m_b']
Z1=Z1.loc[newkeys1]
Z1=Z1.reset_index(drop=True)
#Z=Z[Z['zHEL']<0.8]
l1=Z1.index
COVd2 = cov_final1
tempind1=np.array([[3*i,3*i+1,3*i+2] for i in l1])
tempind1=tempind1.flatten(order='c')


n1=586
n1=768
tempind1=np.array([[3*i,3*i+1,3*i+2] for i in [n1]])
tempind1=tempind1.flatten(order='c')

print('Z is:',Z1.iloc[n1].zHEL,'\n COV elements are: \n', COVd2[:,tempind1][tempind1])
df[df['zHEL']== 0.04].cov_elements
COVd2[3*586,3*1039]

Z is: 0.12588 
 COV elements are: 
 [[0.00400566 0.00122963 0.00076209]
 [0.00122963 0.01673918 0.00042064]
 [0.00076209 0.00042064 0.00057336]]


0.0024665518270000457

In [69]:
z=0.30791
for z in [0.0176]:
    print(df[df.zHEL==z ] .index)
    n2=df[df.zHEL==z  ].index
    tempind2=np.array([[3*i,3*i+1,3*i+2] for i in [n2]])
    tempind2=tempind2.flatten(order='c')
    print('Z is:',df.iloc[n2].zHEL,'\n COV elements are: \n',cov_proper[:,tempind2][tempind2])

Index([1488], dtype='int64')
Z is: 1488    0.0176
Name: zHEL, dtype: float64 
 COV elements are: 
 [[ 0.00389759  0.0001611   0.00143117]
 [ 0.0001611   0.01746965 -0.00040234]
 [ 0.00143117 -0.00040234  0.00138065]]


In [73]:
Z1[Z1.zHEL==0.23822]

zHD       mB        x1         c  HOST_LOGMASS  IDSURVEY       RA  \
1039  0.23693  20.8875 -0.956479 -0.086052         10.79         1  323.639   

         DEC    zHD.1     zHEL     zCMB  
1039 -0.8858  0.23693  0.23822  0.23684

In [46]:
df.iloc[1664]

Unnamed: 0      SN2017coa_150.0
zCMB                    0.04045
mB                     16.97215
x1                      0.71195
c                     -0.047302
HOST_LOGMASS            8.76499
IDSURVEY                  150.0
zHEL                       0.04
RA                   132.480301
DEC                   56.098999
x1ERR                   0.31661
cERR                   0.038881
COV_x1_c              -0.000647
cov_elements            0.00553
Name: 1664, dtype: object

In [47]:
print(df[df.zHEL==0.04 ] .index,df[df.zHEL==0.23822 ] .index)

cov_proper[1664,591]
cov_proper[1664,1664]


Index([1664], dtype='int64') Index([591], dtype='int64')


0.001023970626425

In [ ]:
n2=df[df.zHEL==0.01317].index[0]

n2

In [27]:
PAN_new=PAN.loc[newkeys1]
ra1=PAN_new[PAN_new.zHEL<0.8].RA

In [31]:
newest_df=pd.read_csv(path+'/altered_df.csv',index_col=0)
ra2=newest_df.RA
np.where(np.array(ra1)!=np.array(ra2))


(array([], dtype=int64),)

In [16]:
merged_df = pd.merge(newest_df, PAN, on='zHEL', suffixes=('_newest', '_PAN'))
merged_df['RA_match'] = merged_df['RA_newest'] == merged_df['RA_PAN']
merged_df['DEC_match'] = merged_df['DEC_newest'] == merged_df['DEC_PAN']
print(merged_df[['zHEL', 'RA_newest', 'RA_PAN', 'RA_match', 'DEC_newest', 'DEC_PAN', 'DEC_match']])

         zHEL  RA_newest    RA_PAN  RA_match  DEC_newest  DEC_PAN  DEC_match
0     0.00082   210.7740  210.7740      True     54.2737  54.2737       True
1     0.00082   210.7740  210.7740      True     54.2737  54.2737       True
2     0.00082   210.7740  210.7740      True     54.2737  54.2737       True
3     0.00082   210.7740  210.7740      True     54.2737  54.2737       True
4     0.00144   186.8030  186.8030      True      9.4203   9.4203       True
...       ...        ...       ...       ...         ...      ...        ...
2743  0.79000   334.3240   52.5384     False    -17.8802 -27.3174      False
2744  0.79000    52.5384  334.3240     False    -27.3174 -17.8802      False
2745  0.79000    52.5384   52.5384      True    -27.3174 -27.3174       True
2746  0.79100   334.0600  334.0600      True    -17.3956 -17.3956       True
2747  0.79800    36.0396   36.0396      True     -4.9787  -4.9787       True

[2748 rows x 7 columns]


In [18]:
merged_df['RA_PAN']==False

0       False
1       False
2       False
3       False
4       False
        ...  
2743    False
2744    False
2745    False
2746    False
2747    False
Name: RA_PAN, Length: 2748, dtype: bool

In [2]:
      fun: -1174.8817317049131
        x: [-1.930e+01 -1.534e-01 -3.665e-01  1.014e-01 -2.783e+01
             1.189e-02  1.472e+02  1.777e+01]

IndentationError: unexpected indent (3167248496.py, line 2)

In [26]:
index_cov_sorted_zhel

NameError: name 'index_cov_sorted_zhel' is not defined